### ISSUE TITLE
Screens

### ISSUE THREAD

**Issue by jee-r** [exrat/upload-mktorrent#1]
![up06](https://cloud.githubusercontent.com/assets/10530469/20858906/b737792e-b94f-11e6-8f9b-e1e6f123ca9b.png)
![up05](https://cloud.githubusercontent.com/assets/10530469/20858909/b784404c-b94f-11e6-8ebe-917946139352.png)
![up04](https://cloud.githubusercontent.com/assets/10530469/20858908/b776b904-b94f-11e6-8a33-b83e8986c9a0.png)
![up03](https://cloud.githubusercontent.com/assets/10530469/20858910/b7885880-b94f-11e6-9c8e-c633874a5e39.png)
![up02](https://cloud.githubusercontent.com/assets/10530469/20858911/b7895974-b94f-11e6-944f-54e85717689a.png)
![up01](https://cloud.githubusercontent.com/assets/10530469/20858907/b764e422-b94f-11e6-9480-722e7c3c2926.png)

**Comment by exrat** [comment]
C'est toujours pas bon, faut que tu clics chez toi en haut sur "pull request" et "new pull request"
Je suis pas bien fort avec github (je précise !) mais ça doit être ça la manip pour me pousser ta modif ;)
Ex.

**Comment by jee-r** [comment]
C'est bon ? 

Moi non plus je suis pas bien fort avec github c'est ma première PR 😃

**Comment by exrat** [comment]
Ouais ça a l'air ok, je vais tenter le coup du merge, on verra bien ce qu'il en ressort, au pire j'ai un bak ^^
